# Site Settings
# You can change the settings below in order to customize your website.
name: "ProjectVW.com"
title: "ProjectVW.com - 1973 Volkswagen Super Beetle"
description: "Have you seen my 1973 VW Super Beetle?"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: 
google_analytics: 'G-5V10Z3380G'

# disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
url: 'https://www.projectvw.com'

templatemessage: 'Forked from <a target="_blank" href="https://www.chrishammond.com/">Chris Hammond</a>''s <a href="https://jekyllexample.com">JekyllExample.com</a>.'

# Authors
authors:
  chris:
    name: Chris Hammond
    display_name: Chris Hammond
    gravatar: bff097b7cc348bebce39ee1c7694d125
    email: projectvw@christoc.com
    web: https://chrishammond.com
    twitter: https://twitter.com/projectvw
    description: "Founder of ProjectVW.com. Read more at ChrisHammond.com" 

# Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
      
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

# exclude:
#  - /assets/images/*